---
- name: "(iptables: Debian/Ubuntu) ensure HTTP port is allowed"
  iptables:
    chain: INPUT
    rule_num: 1
    source: 10.0.0.0/16
    protocol: tcp
    match: tcp
    destination_port: 80
    jump: ACCEPT
  become: yes

- name: "(iptables: Debian/Ubuntu) ensure HTTPS port is allowed"
  iptables:
    chain: INPUT
    rule_num: 1
    source: 10.0.0.0/16
    protocol: tcp
    match: tcp
    destination_port: 443
    jump: ACCEPT
  become: yes
